language: php
php:
  - 7.2
  - 7.3
  - 7.4
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
  - composer install
script:
  - composer cs-fixer
  - composer static
  - composer tests